apiVersion: v1
kind: ConfigMap
metadata:
  name: eventflow-config
data:
  EVENT_SERVICE_URL: "http://event-service:5001"
  BOOKING_SERVICE_URL: "http://booking-service:5002"
  NOTIFICATION_SERVICE_URL: "http://notification-service:5003"
  ENVIRONMENT: "development"
