apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eventflow-services
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - event-service
          - booking-service
          - notification-service
          - api-gateway
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
