apiVersion: v1
kind: ServiceAccount
metadata:
  name: eventflow-ksa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: eventflow-gke-sa@eventflow-tibame-2026.iam.gserviceaccount.com
